package gauss;

import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lucas
 */
public class Gauss extends javax.swing.JFrame {

    /**
     * Creates new form Gauss
     */
    public Gauss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInsereCoeficientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCoeficientes = new javax.swing.JTable();
        jButtonMEG = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableInsereConstantes = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableConstantes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableIncognitas = new javax.swing.JTable();
        jButtonGaussSeidel = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableChuteInicial = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableMMQ = new javax.swing.JTable();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonMMQ = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número de incógnitas");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jTableInsereCoeficientes.setModel(modelInsereCoeficientes);
        jTableInsereCoeficientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableInsereCoeficientes);

        jTableCoeficientes.setModel(modelCoeficientes);
        jTableCoeficientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableCoeficientes);

        jButtonMEG.setText("Escalonar por MEG");
        jButtonMEG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMEGActionPerformed(evt);
            }
        });

        jTableInsereConstantes.setModel(modelInsereConstantes);
        jTableInsereConstantes.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableInsereConstantes);

        jTableConstantes.setModel(modelConstantes);
        jTableConstantes.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTableConstantes);

        jLabel2.setText("Atenção aos 0's");

        jTableIncognitas.setModel(modelIncognitas);
        jTableIncognitas.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTableIncognitas);

        jButtonGaussSeidel.setText("Gauss-Seidel");
        jButtonGaussSeidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGaussSeidelActionPerformed(evt);
            }
        });

        jTableChuteInicial.setModel(modelChuteInicial);
        jTableChuteInicial.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTableChuteInicial);

        jTableMMQ.setModel(modelMMQ);
        jTableMMQ.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(jTableMMQ);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(4, 2, 100, 1));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        jLabel3.setText("Número de coletas");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("MMQ: f(x) = a0 + a1*x + a2*x² + a3*x³...");

        jButtonMMQ.setText("MMQ");
        jButtonMMQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMMQActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>A, B, C... : Coeficientes<br> ?: Incógnitas<br> b : Termos independentes</html>");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(10.0F);
        jSeparator1.setAlignmentY(10.0F);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setAlignmentX(10.0F);
        jSeparator2.setAlignmentY(10.0F);

        jLabel6.setText("Resultado:");

        jSeparator3.setAlignmentX(10.0F);
        jSeparator3.setAlignmentY(10.0F);
        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jTextField1.setText("Insira x (opcional)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(502, 502, 502)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(192, 192, 192)
                                                .addComponent(jButtonMEG, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(21, 21, 21)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonGaussSeidel)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonMMQ, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jButtonMEG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButtonGaussSeidel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMMQ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel modelInsereCoeficientes = new DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "A", "B"
            }
        ) {
            @Override
            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        };
    DefaultTableModel modelInsereConstantes = new DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "b"
            }
        ) {
            @Override
            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        };
            
    DefaultTableModel modelCoeficientes = new DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "c1", "c2"
            }
        ) {
            @Override
            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        };
    DefaultTableModel modelConstantes = new DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "b"
            }
        ) {
            @Override
            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        };
    DefaultTableModel modelIncognitas = new DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "?"
            }
        ) {
            @Override
            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        };
    DefaultTableModel modelChuteInicial = new DefaultTableModel(
            new Object [][] {
                {"-"},
                {"0"}
            },
            new String [] {
                "Chute inicial"
            }
        );
    DefaultTableModel modelMMQ = new DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "x", "y"
            }
        ) {
            @Override
            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        };
    
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        modelInsereCoeficientes.setRowCount((int) jSpinner1.getValue());
        modelInsereCoeficientes.setColumnCount((int) jSpinner1.getValue());

        modelInsereConstantes.setRowCount((int) jSpinner1.getValue());
        modelInsereConstantes.setColumnCount(1);
        modelInsereConstantes.setColumnIdentifiers(new String [] {"b"});

        modelChuteInicial.setRowCount((int) jSpinner1.getValue());
        modelChuteInicial.setColumnCount(1);
        modelChuteInicial.setColumnIdentifiers(new String [] {"Chute inicial"});
    }//GEN-LAST:event_jSpinner1StateChanged

    public void metodoDaEliminacao(){
        double fator;
        modelCoeficientes.setRowCount((int) jTableInsereCoeficientes.getRowCount());
        modelCoeficientes.setColumnCount((int) jTableInsereCoeficientes.getColumnCount());
        
        modelConstantes.setRowCount((int) jTableInsereConstantes.getRowCount());
        modelConstantes.setColumnCount(1);
        modelConstantes.setColumnIdentifiers(new String [] {"b"});
        
        modelIncognitas.setRowCount((int) jTableInsereConstantes.getRowCount());
        modelIncognitas.setColumnCount(1);
        modelIncognitas.setColumnIdentifiers(new String [] {"?"});
        
        //copia os valores
        for (int i = 0; i < jTableInsereCoeficientes.getColumnCount(); i++) {
            for (int j = 0; j < jTableInsereCoeficientes.getColumnCount(); j++) {
                            jTableCoeficientes.setValueAt(jTableInsereCoeficientes.getValueAt(i, j), i, j);
            }
            jTableConstantes.setValueAt(jTableInsereConstantes.getValueAt(i, 0), i, 0);
        }
        
        //0 index based
        int pivo = 0; //qual linha está como pivô
        
                //atencao quando for 0 tem que trocar a posicao de linha por uma linha sem 0!!!
        System.out.println("MEG");
        for (int col = 0; col < jTableCoeficientes.getColumnCount(); col++) { // anda pelas colunas
            //atencao aqui pode ser 0!!! tem q trocar caso seja
            double cPivo = Double.valueOf(jTableCoeficientes.getValueAt(pivo, col).toString());
            
            for (int line = col + 1; line < jTableCoeficientes.getRowCount(); line++) {// desce pela linha
                //checa se o valor do coeficiente em analise é zero
                if (Double.valueOf(jTableCoeficientes.getValueAt(line, col).toString()) == 0){continue;}
                //checa se o pivo é zero
                if (Double.valueOf(jTableCoeficientes.getValueAt(pivo, col).toString()) == 0) {
                    trocaLinhas(pivo, line);
                    cPivo = Double.valueOf(jTableCoeficientes.getValueAt(pivo, col).toString());
                }
                    
                fator = Double.valueOf(jTableCoeficientes.getValueAt(line, col).toString())/cPivo; //pode ser zero!
                System.out.println("fator = " + fator);

                for (int c = col; c < jTableCoeficientes.getColumnCount(); c++) {// percorre dentro da linha (pelas colunas) para mudar os coeficientes
                    double valorCoef = Double.valueOf(jTableCoeficientes.getValueAt(pivo, c).toString())*fator - Double.valueOf(jTableCoeficientes.getValueAt(line, c).toString());
                    System.out.println("valorCoef = " + valorCoef);
                    jTableCoeficientes.setValueAt(valorCoef, line, c);
                }
                jTableConstantes.setValueAt(Double.valueOf(jTableConstantes.getValueAt(pivo, 0).toString())*fator - Double.valueOf(jTableConstantes.getValueAt(line, 0).toString()), line, 0);
            }
            pivo++;
        }
        
        //descobre as incognitas apos o escalonamento
        double[] incognitas = new double[jTableConstantes.getRowCount()];
        //Arrays.fill(incognitas, 0);

        //percorre da ultima linha à primeira achando as incognitas
        for (int l = jTableCoeficientes.getRowCount()-1; l >=0; l--) {
            double coeficiente = Double.valueOf(jTableCoeficientes.getValueAt(l, l).toString());
            incognitas[l] = (Double.valueOf(jTableConstantes.getValueAt(l, 0).toString()) - soma(l, incognitas, jTableCoeficientes))/coeficiente;
            modelIncognitas.setValueAt(incognitas[l], l, 0);
            System.out.println("incógnita[" + l + "] = " + incognitas[l]);
        }
        System.out.println();
    }
    
    public void gaussSeidel(){
        double incognitas[] = new double[jTableChuteInicial.getRowCount()];
        
        //preenche vetor das incognitas
        for (int i = 1; i < jTableChuteInicial.getRowCount(); i++) {
            if (jTableChuteInicial.getValueAt(i, 0) != null){
                incognitas[i]  = Double.valueOf(jTableChuteInicial.getValueAt(i, 0).toString());
            }
        }
        
        System.out.println("Gauss-Seidel");
        //iterações do método
        for (int r = 0; r < 100; r++) {
            boolean continuar = false;
            System.out.println(r+1);
            for (int l = 0; l < jTableChuteInicial.getRowCount(); l++) {
                double coeficiente = Double.valueOf(jTableInsereCoeficientes.getValueAt(l, l).toString());
                double comparador = incognitas[l];
                incognitas[l] = (Double.valueOf(jTableInsereConstantes.getValueAt(l, 0).toString()) - soma(l, incognitas, jTableInsereCoeficientes))/coeficiente;
                //checa se o modulo da diferenca entre o valor antigo e o novo é muito pequeno
                if (Math.abs(comparador - incognitas[l]) > 0.1E-16) continuar = true;
                //modelIncognitas.setValueAt(incognitas[l], l, 0);
                System.out.println("incógnita[" + l + "] = " + incognitas[l]);
            }
            System.out.println();
            if (continuar == false) break;
        }
        /*2 variaveis:
        double x; //Double.valueOf(jTableChuteInicial.getValueAt(0, 0).toString());//desnecessario
        double y = Double.valueOf(jTableChuteInicial.getValueAt(1, 0).toString());
        
        for (int r = 0; r < 100; r++) {
            x = (Double.valueOf(jTableInsereConstantes.getValueAt(0, 0).toString()) - Double.valueOf(jTableInsereCoeficientes.getValueAt(0, 1).toString())*y)/Double.valueOf(jTableInsereCoeficientes.getValueAt(0, 0).toString());
            y = (Double.valueOf(jTableInsereConstantes.getValueAt(1, 0).toString()) - Double.valueOf(jTableInsereCoeficientes.getValueAt(1, 0).toString())*x)/Double.valueOf(jTableInsereCoeficientes.getValueAt(1, 1).toString());
            System.out.print("x[" + (r+1) + "] = " + x);
            System.out.println(" y[" + (r+1) + "] = " + y + " \numColetas " );
        }*/
    }
    
    private void jButtonMEGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMEGActionPerformed
        // TODO add your handling code here:
        metodoDaEliminacao();
    }//GEN-LAST:event_jButtonMEGActionPerformed

    private void jButtonGaussSeidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGaussSeidelActionPerformed
        // TODO add your handling code here:
        gaussSeidel();
    }//GEN-LAST:event_jButtonGaussSeidelActionPerformed

    public double somatorio1Var(int exp){
        //exp é o expoente da incognita desejada
        double soma = 0;
        for (int row = 0; row < jTableMMQ.getRowCount(); row++) {
            soma += Math.pow(Double.valueOf(jTableMMQ.getValueAt(row, 0).toString()), exp);
        }
        return soma;
    }

    public double somatorio2Var(int exp){
        //exp é o expoente de X aqui
        double soma = 0;
        for (int row = 0; row < jTableMMQ.getRowCount(); row++) {
           //Soma de Y*(X**exp)
            soma += ( Double.valueOf(jTableMMQ.getValueAt(row, 1).toString()) ) * Math.pow( (Double.valueOf(jTableMMQ.getValueAt(row, 0).toString()) ), exp );
        }
        return soma;
    }
    
    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
        modelMMQ.setRowCount((int) jSpinner2.getValue());
        modelMMQ.setColumnCount(2);
        modelMMQ.setColumnIdentifiers(new String [] {"x", "y"});
        
        if ((int)jSpinner1.getValue() > (int)jSpinner2.getValue()) jSpinner1.setValue((int)jSpinner2.getValue());
    }//GEN-LAST:event_jSpinner2StateChanged

    public void mmq(){
        //so faz sentido calcular um numero de coeficientes <= numero de coletas
        //ou seja, um numero de incognitas < que o numero de coletas
        //um teorema da algebra garante que o polinomio interpolador é de grau menor que o numero de coletas
        if ((int) jSpinner1.getValue() > (int) jSpinner2.getValue()) jSpinner1.setValue((int) jSpinner2.getValue());
        
        int numIncognitas = (int) jSpinner1.getValue();
        int numColetas = (int) jSpinner2.getValue();
        
        //vetores dos somatorios de X**index e YX**index
        double somatoriosX[] = new double[(numIncognitas-1)*2 + 1];
        //double somatoriosYX[] = new double[numIncognitas];
        
        //preenche os somatorios de X**index
        for (int i = 0; i < somatoriosX.length; i++) {
            somatoriosX[i] = somatorio1Var(i);
        }
        
        //preenche as tabelas de inserção de dados
        for (int i = 0; i < jTableInsereCoeficientes.getRowCount(); i++) {
            for (int j = 0; j < jTableInsereCoeficientes.getColumnCount(); j++) {
                jTableInsereCoeficientes.setValueAt(somatoriosX[i + j], i, j);
            }
            jTableInsereConstantes.setValueAt(somatorio2Var(i), i, 0);
        }

        metodoDaEliminacao();
        //jTableChuteInicial.setValueAt(0, 1, 0);
        gaussSeidel();
        

        String s = "<html>MMQ Regressão polinomial: f(x) = " + jTableIncognitas.getValueAt(0, 0) +
                " + " + jTableIncognitas.getValueAt(1, 0) + "x";

        JTextPane jTextPane = new JTextPane();
        jTextPane.setContentType("text/html");
        
        for (int i = 2; i < numIncognitas; i++) {
            String htmlText = "x<sup>" + String.valueOf(i) + "</sup>";
            s += " + " + jTableIncognitas.getValueAt(i, 0) + htmlText;
        }
        s += "</html>";
        jTextPane.setText(s);
        jLabel4.setText(s);
        
        try {
            if (Double.valueOf(jTextField1.getText()) != null){
                double x = Double.valueOf(jTextField1.getText());
                double y=0;
                
                for (int i = 0; i < numIncognitas; i++) {
                    y += Double.valueOf(jTableIncognitas.getValueAt(i, 0).toString())*Math.pow(x, i);
                }
                
                JOptionPane.showMessageDialog(null, String.valueOf("f(" + Double.valueOf(jTextField1.getText()) + ") = " + y),"MMQ",JOptionPane.PLAIN_MESSAGE);}
        } catch (java.lang.NumberFormatException e){
        }
        
            System.out.println("R²: " + (1 - somaQuadraticaResidual()/somaQuadraticaTotal() ) );
            System.out.println("Erro Quadrático: " + Math.sqrt(somaQuadraticaResidual()) + "\n");
    }
    
    private void jButtonMMQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMMQActionPerformed
        // TODO add your handling code here:
        mmq();
    }//GEN-LAST:event_jButtonMMQActionPerformed

    public double somaQuadraticaResidual(){
        //calcula a somatorio (Yobservado - Yprevisto)^2
        double SQResidual = 0;
        
        //y = a0 + a1*x¹ + a2*x² + a3*x³...
        double coeficientes[] = new double[(int)jSpinner1.getValue()];
        
        //preenche o vetor dos coeficientes
        for (int i = 0; i < coeficientes.length; i++) {
            coeficientes[i] = Double.valueOf(jTableIncognitas.getValueAt(i, 0).toString());
        }
        
        for (int row = 0; row < jTableMMQ.getRowCount(); row++) {
            double x = Double.valueOf(jTableMMQ.getValueAt(row, 0).toString());
            double y = Double.valueOf(jTableMMQ.getValueAt(row, 1).toString());

            double yPrevisto = 0;
            for (int i = 0; i < coeficientes.length; i++) { //calcular o y previsto
                yPrevisto += coeficientes[i]*Math.pow(x, i);
            }
            //System.out.println("SQR " + Math.pow(y - (yPrevisto/*:= a0 + a1*x¹ + a2*x² + a3*x³...*/), 2));
            SQResidual += Math.pow(y - yPrevisto, 2);
        }

/*        //y = c + mx
        double c = Double.valueOf(jTableIncognitas.getValueAt(0, 0).toString()); 
        double m = Double.valueOf(jTableIncognitas.getValueAt(1, 0).toString());
        
        for (int row = 0; row < jTableDados.getRowCount(); row++) {
            double x = Double.valueOf(jTableDados.getValueAt(row, 0).toString());
            double y = Double.valueOf(jTableDados.getValueAt(row, 1).toString());
            //System.out.println(Math.pow(y - (c + m*x), 2));
            SQResidual += Math.pow(y - (c + m*x), 2);
        }*/
        return SQResidual;
    }
    
    public double somaQuadraticaTotal(){
        //calcula a somatorio (Yobservado - médiaDosY)^2
        double SQTotal = 0;
        double mediaDosY = 0;

        for (int row = 0; row < jTableMMQ.getRowCount(); row++) {
            mediaDosY += Double.valueOf(jTableMMQ.getValueAt(row, 1).toString());
        }
        mediaDosY = mediaDosY/(double) (int) jSpinner2.getValue();
        //System.out.println("mediaDosY = " + mediaDosY);
        
        for (int row = 0; row < jTableMMQ.getRowCount(); row++) {
            double y = Double.valueOf(jTableMMQ.getValueAt(row, 1).toString());
            //System.out.println(Math.pow(y - mediaDosY, 2));
            SQTotal += Math.pow(y - mediaDosY, 2);
        }
        return SQTotal;
    }
    
    
    public void trocaLinhas(int l1, int l2){
        Object reserva;
        for (int c = 0; c < jTableCoeficientes.getColumnCount(); c++) {
            reserva = jTableCoeficientes.getValueAt(l1, c);
            jTableCoeficientes.setValueAt(jTableCoeficientes.getValueAt(l2, c), l1, c);
            jTableCoeficientes.setValueAt(reserva, l2, c);
        }
        reserva = jTableConstantes.getValueAt(l1, 0);
        jTableConstantes.setValueAt(jTableConstantes.getValueAt(l2, 0), l1, 0);
        jTableConstantes.setValueAt(reserva, l2, 0);

        System.out.println("trocou " + l1 + " por " + l2);
    }
    
    public double soma(int l, double[] incognitas, javax.swing.JTable jTable){
        double soma = 0;

        for (int c = 0; c < jTable.getColumnCount(); c++) {
            if (c == l) {continue;}
            soma += Double.valueOf(jTable.getValueAt(l, c).toString())*incognitas[c];
        }
        return soma;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Gauss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGaussSeidel;
    private javax.swing.JButton jButtonMEG;
    private javax.swing.JButton jButtonMMQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTableChuteInicial;
    private javax.swing.JTable jTableCoeficientes;
    private javax.swing.JTable jTableConstantes;
    private javax.swing.JTable jTableIncognitas;
    javax.swing.JTable jTableInsereCoeficientes;
    private javax.swing.JTable jTableInsereConstantes;
    private javax.swing.JTable jTableMMQ;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
